FROM python:3.6

ENV FLASK_APP src/app
ENV FLASK_ENV development flask run
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_RUN_PORT 8000

RUN mkdir -p /usr/src/app
ENV HOME=/usr/src/app
WORKDIR $HOME

ADD requirements.txt $HOME
RUN pip install -r requirements.txt
ADD . $HOME
